import type {
  StoryChoice,
  StoryDefinition,
  StoryStage,
} from './story-types.ts';

const choose = (
  id: string,
  label: string,
  text: string,
  next: string,
  details: Partial<Omit<StoryChoice, 'id' | 'label' | 'text' | 'next'>> = {},
): StoryChoice => ({ id, label, text, next, minutes: 15, ...details });
const end = (
  id: string,
  title: string,
  person: string,
  text: string,
): StoryStage => ({
  id,
  title,
  person,
  text,
  objective: '故事已结束，可回看此前选择。',
  choices: [],
  ending: true,
});
const leave = (text: string) =>
  choose('decline', '婉辞这件事', text, 'declined', { minutes: 0 });

/** Authored decisions define routes; explicitly marked illegal acts may branch on arrest. */
export const STORIES: StoryDefinition[] = [
  {
    id: 'tea-price',
    title: '一张茶单，两种生意',
    focus: 'trade',
    opening: 'opening',
    stages: [
      {
        id: 'opening',
        title: '茶行门前',
        person: '茶商许衡',
        text: '许衡捏着外埠茶单：船已泊岸，买家却在观望。他想邀茶客试饮；掮客罗七却提议传一句“茶船误期”，等牌价抬高再卖。许衡请你自己选。',
        objective:
          '选择招徕买家、联络来货，或冒险散布紧缺消息。市场也可随时自行奔走。',
        choices: [
          choose(
            'promote',
            '替许衡招徕茶客',
            '你拿着真实货样去请买家，许衡答应若有客人登门便请你补齐茶席。',
            'tea-table',
            { minutes: 0, influence: { method: 'promote', good: 'tea' } },
          ),
          choose(
            'import',
            '帮船主联络来货',
            '你请船主公开货单，改走供货合作。行情是否回落，要看各家肯不肯收货。',
            'ship-letter',
            { minutes: 0, influence: { method: 'import', good: 'tea' } },
          ),
          choose(
            'rumor',
            '接受罗七的假消息生意',
            '你决定冒险虚构茶船误期。罗七不会替你承担官府追查。',
            'speculation',
            {
              minutes: 0,
              influence: { method: 'rumor', good: 'tea', caughtNext: 'court' },
            },
          ),
          leave('你不接这笔生意，继续按自己的判断买卖。'),
        ],
      },
      {
        id: 'tea-table',
        title: '真实的一席茶',
        person: '许衡',
        deadlineMinutes: 2880,
        timeout: 'late',
        text: '几位茶客愿意坐下来尝货。许衡不保证牌价，只请你备四个炊饼，按100文结算，往后带你认识收货行商。',
        objective: '两日内交付炊饼4个，或放下茶席。',
        choices: [
          choose(
            'deliver',
            '交付茶席炊饼',
            '茶席摆成，许衡把你介绍给相熟行商。此后做生意靠货样与履约。',
            'honest-end',
            {
              destination: 'market',
              cost: { goods: { bread: 4 } },
              reward: { cash: 100, customer: 'merchant', reputation: 1 },
            },
          ),
          leave('你说明备不齐茶席，许衡另找人采购。'),
        ],
      },
      {
        id: 'ship-letter',
        title: '船主的回信',
        person: '船主周成',
        waitMinutes: 1440,
        text: '周成请你把真实到货单交给摆渡人存证。他愿意介绍沿河运货的人，但不会许诺低价或包销。',
        objective: '花时间核对实货，建立运输合作。',
        choices: [
          choose(
            'verify',
            '核对来货并认门',
            '周成与摆渡人一起签下货单。你有了能直接核对船期的熟人。',
            'supply-end',
            {
              minutes: 45,
              cost: { stamina: 8 },
              reward: { customer: 'ferryman', reputation: 1 },
            },
          ),
          leave('你没有继续跟单，船主自行安排卸货。'),
        ],
      },
      {
        id: 'speculation',
        title: '抬价之后',
        person: '罗七',
        text: '罗七提醒你：没人保证接盘，06:00就会重新议价。账上的浮盈只有实际卖出才算数。他还想让你下次继续，你也可以就此抽身。',
        objective: '自行到市场按现价买卖；决定是否公开更正消息。',
        choices: [
          choose(
            'correct',
            '向许衡更正假消息',
            '你向许衡说明消息虚构。他不再替罗七担保，但愿意日后看你如何履约。',
            'corrected-end',
            { minutes: 30, reward: { reputation: 1 } },
          ),
          choose(
            'leave-ring',
            '与罗七断开来往',
            '你收好账本独自离开，不再替罗七传话。涨跌与库存留给自己处理。',
            'risk-end',
          ),
        ],
      },
      {
        id: 'court',
        title: '茶单成了证据',
        person: '市司书吏',
        text: '实到货单戳穿了误期消息。罚款已扣，拘押必须服满。期满后可以向许衡说明原委，或承担责任就此离开。',
        objective: '先服满拘押，再决定如何面对受牵连的茶商。',
        choices: [
          choose(
            'apologize',
            '向许衡赔礼说明',
            '你认下自己的选择。许衡收下道歉，却不肯给你介绍买家；这段交情须从头来过。',
            'corrected-end',
            { minutes: 30 },
          ),
          choose(
            'accept',
            '认罚结束此事',
            '你带着罚款记录离开市司，错过的货期和库存仍须自行收拾。',
            'risk-end',
          ),
        ],
      },
      end(
        'honest-end',
        '凭货样结交',
        '许衡',
        '茶席成了新的供货关系，价格仍随市况起落。',
      ),
      end(
        'supply-end',
        '沿河的熟人',
        '周成',
        '真实货单连起了运输合作，行情回落也能成为采购机会。',
      ),
      end(
        'corrected-end',
        '更正与代价',
        '许衡',
        '你更正了虚构的消息，已经发生的费用、涨跌与处罚不会撤销。',
      ),
      end(
        'risk-end',
        '留下自己的账',
        '罗七',
        '这场冒险结束，手里的货与实际盈亏留在账本中。',
      ),
      end(
        'late',
        '错过茶席',
        '许衡',
        '茶席没有等到约定的炊饼，许衡另找人供货，报酬与介绍作罢。',
      ),
      end('declined', '各做各的生意', '许衡', '你没有继续承担这件事。'),
    ],
  },
  {
    id: 'broken-eggs',
    title: '一篮碎蛋与一纸欠账',
    focus: 'neighbors',
    opening: 'opening',
    stages: [
      {
        id: 'opening',
        title: '桥头之后',
        person: '陈婆婆',
        text: '陈婆婆在茶棚摊开湿了半边的货单。食肆说少了四枚蛋，脚夫却说出门时数过。她怕误了席面，又不甘心认下一笔糊涂账。',
        objective: '选择帮助摊主补货，或沿脚夫的路线查证。',
        choices: [
          choose(
            'advance',
            '帮她垫付急用',
            '你留下20文。陈婆婆答应请食肆把旧单找出来，明日给你口信。',
            'letter',
            { cost: { cash: 20 }, reward: { reputation: 1 } },
          ),
          choose(
            'escort',
            '陪阿成核对送货路线',
            '你陪阿成走过桥头和后厨。他认出了收货时另用的那只小篮。',
            'porter',
            { minutes: 30, cost: { stamina: 10 } },
          ),
          leave('你说明近日无暇，陈婆婆收起货单另找人商量。'),
        ],
      },
      {
        id: 'letter',
        title: '托来的口信',
        person: '陈婆婆',
        waitMinutes: 1440,
        text: '陈婆婆捎话：食肆愿意拿出账簿，但三日内得给席面一个交代。她问你愿意先补四枚蛋，还是先看清旧账。',
        objective: '决定先解决货物缺口还是调查责任。',
        choices: [
          choose(
            'supply',
            '答应备四枚蛋',
            '你接下补货的事；三日内交付，食肆约定付90文。',
            'supply',
          ),
          choose(
            'audit',
            '先核对账簿',
            '你请陈婆婆暂缓认账，带着旧货单去见掌柜。',
            'audit',
            { minutes: 30, cost: { stamina: 5 } },
          ),
          leave('你没有接下新的承诺，陈婆婆会继续找人帮忙。'),
        ],
      },
      {
        id: 'porter',
        title: '后厨的第二只篮',
        person: '脚夫阿成',
        text: '阿成记起，后厨把四枚蛋单放在一只小篮里送往点心房。跑堂肯作证，但要等他交班。',
        objective: '花时间取得证言，或协商先按小篮分开记账。',
        choices: [
          choose(
            'witness',
            '等跑堂交班作证',
            '跑堂在纸上画了小篮的记号，证实四枚蛋已交给点心房。',
            'reconcile',
            { minutes: 60, cost: { stamina: 5 }, reveal: 'basket-witness' },
          ),
          choose(
            'separate',
            '请后厨另列点心房账',
            '后厨答应暂列两笔账，阿成带你去请双方当面确认。',
            'reconcile',
            { minutes: 30, cost: { stamina: 10 } },
          ),
        ],
      },
      {
        id: 'audit',
        title: '两本账',
        person: '食肆掌柜',
        text: '厨房记的是整篮，点心房记的是领用。两本账里的四枚蛋重叠了。掌柜愿意听解释，也问你是否愿意替双方先填缺口。',
        objective: '凭账目厘清责任，或承担补货。',
        choices: [
          choose(
            'explain',
            '逐笔对清领用记录',
            '掌柜在领用栏划出重记的一笔，请陈婆婆和阿成一起到场。',
            'reconcile',
            { minutes: 45, cost: { stamina: 8 }, reveal: 'double-entry' },
          ),
          choose(
            'fill',
            '先把席面备齐',
            '你接下四枚蛋的补货，掌柜约定90文，三日内交齐。',
            'supply',
          ),
        ],
      },
      {
        id: 'supply',
        title: '开席之前',
        person: '食肆掌柜',
        deadlineMinutes: 4320,
        timeout: 'late',
        text: '掌柜把收货木牌交给你，席面不能再拖。四枚完整鸡蛋可以用自己的库存，也可以去市场采购。',
        objective: '截止前向食肆交付鸡蛋4枚，报酬90文。',
        choices: [
          choose(
            'deliver',
            '交付四枚鸡蛋',
            '四枚蛋逐枚验收。掌柜付了90文，陈婆婆终于能安心摆摊。',
            'supplier-end',
            {
              destination: 'market',
              minutes: 30,
              cost: { goods: { egg: 4 } },
              reward: { cash: 90, customer: 'eggSeller', reputation: 1 },
            },
          ),
        ],
      },
      {
        id: 'reconcile',
        title: '把话说在一处',
        person: '陈婆婆与阿成',
        text: '三人在后厨对齐账目，少蛋的误会解开了。陈婆婆想请你收下谢礼，阿成更愿意带你认识码头收货的人。',
        objective: '选择维系摊主人情，或发展运输合作。',
        choices: [
          choose(
            'vendor',
            '陪陈婆婆把账结清',
            '掌柜撤去欠账，陈婆婆请卖蛋的熟人认识你；这件事成了她以后肯托付你的缘由。',
            'vendor-end',
            { minutes: 30, reward: { customer: 'eggSeller', reputation: 2 } },
          ),
          choose(
            'porter',
            '随阿成去码头认门',
            '阿成把你介绍给摆渡人。往后供货订单能直接与他商量。',
            'porter-end',
            {
              minutes: 45,
              cost: { stamina: 5 },
              reward: { customer: 'ferryman', reputation: 1 },
            },
          ),
        ],
      },
      {
        id: 'late',
        title: '席面散后',
        person: '陈婆婆',
        text: '席面已经另行备齐，原来的90文补货约定失效。陈婆婆仍希望把旧账说清，免得下次再吃亏。',
        objective: '选择补救核账，或承认未能完成这次约定。',
        choices: [
          choose(
            'repair',
            '去后厨核对旧账',
            '你为迟到致歉，掌柜仍让你查看领用簿。',
            'audit',
            { minutes: 30, cost: { stamina: 8 } },
          ),
          choose(
            'close',
            '当面说明无法继续',
            '你把事情说清，没有领取未完成的货款；陈婆婆自己去找掌柜。',
            'missed-end',
            { minutes: 15 },
          ),
        ],
      },
      end(
        'supplier-end',
        '席面如期',
        '陈婆婆',
        '这次你是及时补货的人。陈婆婆认识了你的生意，卖蛋熟客也愿意与你往来。',
      ),
      end(
        'vendor-end',
        '账清人熟',
        '陈婆婆',
        '没有多卖一枚蛋，你却替她免去一笔糊涂账。她把你当成能说理的街坊。',
      ),
      end(
        'porter-end',
        '码头有熟人',
        '脚夫阿成',
        '阿成记住了你肯陪他查清事情。摆渡人的供货往来向你开放。',
      ),
      end(
        'missed-end',
        '未赶上的席面',
        '陈婆婆',
        '这次约定未完成。席面照常散去，你没有得到货款或合作介绍。',
      ),
      end(
        'declined',
        '各自忙碌',
        '陈婆婆',
        '你没有许下做不到的承诺。这件事由摊主和食肆自行商量。',
      ),
    ],
  },
  {
    id: 'theatre',
    title: '戏班开演之前',
    focus: 'craft',
    opening: 'opening',
    stages: [
      {
        id: 'opening',
        title: '缺了一箱戏衣',
        person: '鼓师柳七',
        text: '戏班的旧衣箱被雨淋透。班主盯着开演日期，裁缝却说湿布不能急着下针。柳七请你看看哪条路来得及。',
        objective: '选择筹布，或协助修补旧衣。',
        choices: [
          choose(
            'cloth',
            '替戏班筹布',
            '班主把用料写成小单，明日请你与衣箱师傅核对。',
            'measure',
          ),
          choose(
            'repair',
            '跟裁缝清点可修的衣服',
            '你翻晾衣箱，发现大半衣服只是接缝松了，未必需要全换。',
            'seams',
            { minutes: 45, cost: { stamina: 10 } },
          ),
          leave('柳七另找人筹措，你没有接下开演的担子。'),
        ],
      },
      {
        id: 'measure',
        title: '两套用料',
        person: '衣箱师傅',
        waitMinutes: 1440,
        text: '师傅列了两套办法：两匹布赶制整衣，或用四束线修补旧衣。班主希望演出体面，演员更在乎穿着顺手。',
        objective: '选择新衣路线或旧衣路线。',
        choices: [
          choose(
            'new',
            '按新衣备料',
            '你答应三日内交两匹布，班主约定付320文。',
            'new-clothes',
          ),
          choose(
            'weave',
            '自己织出两匹戏衣布',
            '师傅愿意多等两日。你接下五日内织成并交付两匹布的约定，报酬320文。',
            'weaving',
          ),
          choose(
            'old',
            '先听演员说旧衣的用处',
            '演员领你看翻身时容易绷开的袖口，裁缝重新估了工。',
            'seams',
            { minutes: 30, cost: { stamina: 5 } },
          ),
        ],
      },
      {
        id: 'seams',
        title: '袖口的旧针脚',
        person: '裁缝阿绫',
        text: '阿绫说只要找准受力的地方，旧衣还撑得过首演。懂纺织的人可以直接标针脚，不懂也能跟着演员排一次身段。',
        objective: '用手艺或排练观察找出修补位置。',
        choices: [
          choose(
            'skill',
            '依针脚标出受力处',
            '你的判断让阿绫省下返工，四束线就够修齐。',
            'mend',
            {
              skill: { id: 'textile', level: 1 },
              minutes: 20,
              reward: { skill: 'textile', xp: 5 },
            },
          ),
          choose(
            'watch',
            '帮演员试穿排练',
            '你反复记下绷线的位置，阿绫照记号改好了针路。',
            'mend',
            { minutes: 60, cost: { stamina: 12 } },
          ),
        ],
      },
      {
        id: 'new-clothes',
        title: '赶制新衣',
        person: '班主',
        deadlineMinutes: 4320,
        timeout: 'rain-check',
        text: '开演前要留出裁衣的时间。班主备好了货款，等你将两匹布送到。',
        objective: '交付布2匹，报酬320文。',
        choices: [
          choose(
            'deliver',
            '把布送入衣箱房',
            '班主验收布匹，付320文，请你演出前再来看看成衣。',
            'curtain-new',
            {
              minutes: 30,
              destination: 'market',
              cost: { goods: { cloth: 2 } },
              reward: { cash: 320 },
            },
          ),
        ],
      },
      {
        id: 'weaving',
        title: '为戏衣织一匹合适的布',
        person: '衣箱师傅',
        deadlineMinutes: 7200,
        timeout: 'rain-check',
        text: '师傅要看这次新织布的紧密程度。你需要先学会纺织、备好织机和麻线，再到生产页织麻布并交货；买来的布不能代替这次试织。',
        objective: '本阶段亲自生产布2匹，并交付布2匹；报酬320文。',
        productionGoal: { good: 'cloth', quantity: 2 },
        choices: [
          choose(
            'deliver',
            '交付亲自织成的戏衣布',
            '师傅验过这次织布的记录和布匹，付320文，请你来看新衣上台。',
            'curtain-new',
            {
              destination: 'market',
              minutes: 30,
              cost: { goods: { cloth: 2 } },
              produced: { good: 'cloth', quantity: 2 },
              reward: { cash: 320, skill: 'textile', xp: 8 },
            },
          ),
        ],
      },
      {
        id: 'mend',
        title: '一针一线',
        person: '裁缝阿绫',
        deadlineMinutes: 4320,
        timeout: 'rain-check',
        text: '旧衣摊在长案上，修补的位置已经标好。阿绫需要四束线，你可在市场备齐再来。',
        objective: '交付线4束并协助穿针，报酬140文。',
        choices: [
          choose(
            'deliver',
            '送线并协助修补',
            '针脚收牢了，阿绫付140文，请你以帮手身份来看首演。',
            'curtain-old',
            {
              minutes: 60,
              destination: 'market',
              cost: { stamina: 8, goods: { thread: 4 } },
              reward: { cash: 140, skill: 'textile', xp: 8 },
            },
          ),
        ],
      },
      {
        id: 'curtain-new',
        title: '新衣登台',
        person: '班主',
        waitMinutes: 720,
        text: '新衣在灯下亮起来。班主向旁边的布庄掌柜介绍你，说这次开演多亏有人按时把货送到。',
        objective: '选择供货介绍，或结清这次生意。',
        choices: [
          choose(
            'meet',
            '与布庄掌柜认门',
            '布庄掌柜记下你的名字，愿意与你谈供货。',
            'new-end',
            { reward: { customer: 'clothier' } },
          ),
          choose(
            'settle',
            '看完首演便告辞',
            '你收好这次买卖的凭据，班主记住了一位守时的供货人。',
            'paid-end',
            { reward: { reputation: 1 } },
          ),
        ],
      },
      {
        id: 'curtain-old',
        title: '旧衣照样上场',
        person: '裁缝阿绫',
        waitMinutes: 720,
        text: '演员翻身时衣袖稳稳展开。阿绫请你留下一起收针，肯把这次改线的诀窍细说一遍。',
        objective: '学习针路，或接受演员的人情介绍。',
        choices: [
          choose(
            'learn',
            '留下复盘针路',
            '你跟阿绫拆看试样，记住了接缝与受力的关系。',
            'craft-end',
            { minutes: 45, reward: { skill: 'textile', xp: 15 } },
          ),
          choose(
            'meet',
            '随演员拜访布庄',
            '演员把修衣经过说给布庄掌柜，介绍你们认识。',
            'new-end',
            { minutes: 30, reward: { customer: 'clothier' } },
          ),
        ],
      },
      {
        id: 'rain-check',
        title: '开演已过',
        person: '柳七',
        text: '戏班借衣完成首演，原来的供货约定失效。柳七仍请你来收拾后台，修补借衣，免得欠下人情。',
        objective: '花时间补救，或结束此事。',
        choices: [
          choose(
            'repair',
            '帮忙整理归还借衣',
            '你陪柳七逐件核清，借衣的人没有为难戏班。',
            'repair-end',
            { minutes: 90, cost: { stamina: 15 }, reward: { reputation: 1 } },
          ),
          choose(
            'leave',
            '说明无暇再帮',
            '你没有领到未交付的报酬，柳七自己去还衣箱。',
            'missed-end',
          ),
        ],
      },
      end(
        'new-end',
        '以布结缘',
        '班主',
        '你成为班主认得的供货人，布庄合作由此开启。',
      ),
      end(
        'paid-end',
        '一场稳妥买卖',
        '班主',
        '买卖结清，首演顺利，你留下了守约的名声。',
      ),
      end(
        'craft-end',
        '灯下的针路',
        '阿绫',
        '你留下的不是一张货单，而是阿绫传授的修衣经验。',
      ),
      end(
        'repair-end',
        '还清借衣人情',
        '柳七',
        '虽未赶上首演，你帮戏班把事后的责任收拾妥当。',
      ),
      end(
        'missed-end',
        '后台另有人忙',
        '柳七',
        '戏班另寻帮手，原约定已经结束。',
      ),
      end(
        'declined',
        '鼓声从身后传来',
        '柳七',
        '你没有接下委托，戏班继续筹措。',
      ),
    ],
  },
  {
    id: 'granary',
    title: '粮埠换主',
    focus: 'trade',
    opening: 'opening',
    stages: [
      {
        id: 'opening',
        title: '交接的封条',
        person: '粮埠老赵',
        text: '粮仓换掌柜，门口两车货谁也不肯签收。老赵说旧账没清，新掌柜说不能替前任认账。',
        objective: '选择核账，或组织一笔独立应急供货。',
        choices: [
          choose(
            'audit',
            '替双方核验封条',
            '你记下封条和车牌，老赵约你明日看出入簿。',
            'seals',
            { minutes: 30, cost: { stamina: 5 } },
          ),
          choose(
            'supply',
            '先问附近食肆的缺口',
            '你挨铺问清需求，没有替任何人认下旧债。',
            'buyers',
            { minutes: 45, cost: { stamina: 8 } },
          ),
          leave('你不卷入这次交接，两位掌柜继续争论。'),
        ],
      },
      {
        id: 'seals',
        title: '同车不同记号',
        person: '老赵',
        waitMinutes: 1440,
        text: '两张车牌的字迹相近，封条却不是同一天贴的。可以请守仓人认印，也可以逐笔复核称重簿。',
        objective: '取得能说明归属的凭据。',
        choices: [
          choose(
            'keeper',
            '请守仓人认印',
            '守仓人认出了先后两批封条，旧货与新货的归属终于分清。',
            'settlement',
            { minutes: 45, cost: { stamina: 8 }, reveal: 'warehouse-seal' },
          ),
          choose(
            'weigh',
            '重核称重簿',
            '你把缺失的零头对应到车次，差额来自两车混记。',
            'settlement',
            { minutes: 60, cost: { stamina: 12 }, reveal: 'weight-record' },
          ),
        ],
      },
      {
        id: 'buyers',
        title: '等米下锅的人',
        person: '磨坊阿七',
        text: '磨坊需要十份粟米，不愿等粮埠吵完。阿七约定三日内交付，付260文；也提醒你别为了他把自家口粮卖空。',
        objective: '决定接下独立供货，或回去协助核账。',
        choices: [
          choose(
            'promise',
            '接下十份粟米',
            '阿七写好260文的收货凭据，三日内有效。',
            'grain-delivery',
          ),
          choose(
            'investigate',
            '先查粮埠能否放货',
            '你带着磨坊的需求回粮埠，开始核验车次。',
            'seals',
            { minutes: 30 },
          ),
        ],
      },
      {
        id: 'grain-delivery',
        title: '磨坊开磨',
        person: '阿七',
        deadlineMinutes: 4320,
        timeout: 'late',
        text: '十份粟米到齐才能排这一轮磨。买入与搬运的成本由你自行安排，交货时一次验收。',
        objective: '交付粟米10份，报酬260文。',
        choices: [
          choose(
            'deliver',
            '向磨坊交粮',
            '阿七收下十份粮，付260文，答应给你介绍常来收面的饼铺。',
            'buyers-result',
            {
              destination: 'market',
              minutes: 45,
              cost: { goods: { grain: 10 } },
              reward: { cash: 260 },
            },
          ),
        ],
      },
      {
        id: 'settlement',
        title: '谁在新单上落名',
        person: '新旧掌柜',
        text: '归属已经明白，双方同意分开记账。新掌柜请你介绍后续买主，老赵则想让你先认识跑船的行商。',
        objective: '选择新仓合作或行商人脉。',
        choices: [
          choose(
            'new-owner',
            '替新仓牵线',
            '新掌柜愿意在五日内按每份16文向你供应最多十份粟米，作为这次核账的谢意。',
            'warehouse-end',
            {
              reward: {
                opportunity: {
                  good: 'grain',
                  quantity: 10,
                  price: 16,
                  days: 5,
                },
                reputation: 1,
              },
            },
          ),
          choose(
            'merchant',
            '随老赵去见行商',
            '行商沈九听完经过，与你交换了供货门路。',
            'merchant-end',
            { minutes: 45, reward: { customer: 'merchant' } },
          ),
        ],
      },
      {
        id: 'buyers-result',
        title: '新磨的面香',
        person: '阿七',
        waitMinutes: 720,
        text: '磨坊开磨后，饼铺孙娘来取面。阿七说明是你及时送来的粮。',
        objective: '认识饼铺，或了解粮埠的后续。',
        choices: [
          choose(
            'baker',
            '与孙娘谈往后的供货',
            '孙娘愿意把合适的供货需求交给你看。',
            'baker-end',
            { reward: { customer: 'baker' } },
          ),
          choose(
            'dock',
            '回粮埠问问交接',
            '老赵已办完交接，看你对货路有兴趣，带你认识沈九。',
            'merchant-end',
            { minutes: 45, reward: { customer: 'merchant' } },
          ),
        ],
      },
      {
        id: 'late',
        title: '磨坊改了排期',
        person: '阿七',
        text: '阿七已从别处备粮，260文的约定失效。他愿意听你说明情况，但不会再收这一单。',
        objective: '当面收尾或重新从核账入手。',
        choices: [
          choose(
            'audit',
            '去帮老赵核清交接',
            '你回粮埠重新问起封条，不再占用磨坊的排期。',
            'seals',
            { minutes: 30 },
          ),
          choose(
            'end',
            '结清口头约定',
            '你说明未能交付，阿七收回了凭据。',
            'missed-end',
          ),
        ],
      },
      end(
        'warehouse-end',
        '新仓开门',
        '新掌柜',
        '粮埠交接完成。有限熟客货源已开放，过期或购足即结束。',
      ),
      end(
        'merchant-end',
        '水路的新面孔',
        '沈九',
        '你认识了行商，今后可查看他的供货机会。',
      ),
      end(
        'baker-end',
        '从粮到饼',
        '孙娘',
        '及时供粮让你与饼铺建立了实际来往。',
      ),
      end(
        'missed-end',
        '错过开磨',
        '阿七',
        '这次没有货款，也没有因未交付而获得介绍。',
      ),
      end('declined', '封条仍在门上', '老赵', '你没有参与粮埠交接。'),
    ],
  },
  {
    id: 'embroidery',
    title: '绣坊师徒',
    focus: 'craft',
    opening: 'opening',
    stages: [
      {
        id: 'opening',
        title: '被收起的鞋样',
        person: '绣娘阿秀',
        text: '阿秀的新鞋样被师傅压在账簿下。师傅担心交期，阿秀却不愿一辈子只照旧样描线。',
        objective: '选择稳住旧订单，或帮阿秀准备独立样品。',
        choices: [
          choose(
            'master',
            '先听师傅的交期安排',
            '师傅把原订单摊给你，请你先看不能耽误的部分。',
            'old-order',
            { minutes: 30 },
          ),
          choose(
            'pupil',
            '请阿秀讲讲新样',
            '阿秀拿出试样，解释哪几处针路是自己改过的。',
            'new-pattern',
            { minutes: 30 },
          ),
          leave('你把鞋样放回桌上，让师徒自行商量。'),
        ],
      },
      {
        id: 'old-order',
        title: '先把旧约办妥',
        person: '绣坊师傅',
        text: '旧订单还差三束线。师傅约定三日内补齐付105文，但希望你也能劝阿秀别与客人争执。',
        objective: '承接线料，或先为师徒安排一次谈话。',
        choices: [
          choose(
            'materials',
            '答应补三束线',
            '师傅写下105文的价款和三日交期。',
            'thread-delivery',
          ),
          choose(
            'talk',
            '先让师徒各说难处',
            '你留下一段不赶工的时间，让阿秀展示新样的实际用处。',
            'new-pattern',
            { minutes: 60, cost: { stamina: 8 } },
          ),
        ],
      },
      {
        id: 'new-pattern',
        title: '针路要经得起试',
        person: '阿秀',
        text: '新样好看，却没人试过久穿。懂纺织可以检查接缝，不懂也可帮她记录试穿时的磨损位置。',
        objective: '取得可靠试样记录。',
        choices: [
          choose(
            'craft',
            '检查线路和接缝',
            '你指出鞋口两处容易磨断的线，阿秀照着改好了。',
            'sample',
            {
              skill: { id: 'textile', level: 1 },
              minutes: 30,
              reward: { skill: 'textile', xp: 5 },
            },
          ),
          choose(
            'trial',
            '陪着试穿并记下磨痕',
            '阿秀来回走了几趟，你把磨痕逐一画在纸上。',
            'sample',
            { minutes: 75, cost: { stamina: 12 } },
          ),
        ],
      },
      {
        id: 'thread-delivery',
        title: '旧单的最后三束线',
        person: '绣坊师傅',
        deadlineMinutes: 4320,
        timeout: 'late',
        text: '师傅留出绣架等线料，阿秀也答应先把手头旧单完成。',
        objective: '交付线3束，报酬105文。',
        choices: [
          choose(
            'deliver',
            '把三束线交给师傅',
            '师傅验收后付105文，留你看这批成品。',
            'master-result',
            {
              minutes: 30,
              destination: 'market',
              cost: { goods: { thread: 3 } },
              reward: { cash: 105 },
            },
          ),
        ],
      },
      {
        id: 'sample',
        title: '一匹布的试样',
        person: '阿秀',
        text: '阿秀打算独立留一件试样，请你提供一匹布；她明确说付不起货款，但愿意把改样心得教给你。',
        objective: '选择投入布匹支持新样，或回去稳定旧订单。',
        choices: [
          choose(
            'support',
            '交一匹布做试样',
            '你交出布匹，阿秀花心思把新针路完整做了一遍，请你次日看样。',
            'pupil-result',
            {
              minutes: 30,
              destination: 'market',
              cost: { goods: { cloth: 1 } },
            },
          ),
          choose(
            'old',
            '先完成师傅的旧单',
            '你说明眼下投入太大，阿秀愿意先缓一缓新样。',
            'old-order',
          ),
        ],
      },
      {
        id: 'master-result',
        title: '旧约守住以后',
        person: '绣坊师傅',
        waitMinutes: 720,
        text: '成品交出去，师傅的眉头松了。他肯带你认识布庄，也愿意把选线经验讲给你。',
        objective: '选择商路或手艺。',
        choices: [
          choose(
            'trade',
            '请师傅介绍布庄',
            '布庄掌柜愿意与你谈稳定供货。',
            'master-end',
            { reward: { customer: 'clothier' } },
          ),
          choose(
            'learn',
            '留在绣架旁学选线',
            '师傅拿旧样解释了选线的差别，你记下了实际手法。',
            'craft-end',
            { minutes: 60, reward: { skill: 'textile', xp: 20 } },
          ),
        ],
      },
      {
        id: 'pupil-result',
        title: '鞋样终于挂出来',
        person: '阿秀',
        waitMinutes: 1440,
        text: '新样经住试穿，阿秀在样牌上写下自己的名字。师傅看完没有收走，只说下次要自己算好用料。',
        objective: '一起复盘新针路。',
        choices: [
          choose(
            'review',
            '复盘新样的用料与针路',
            '阿秀把做样过程完整讲给你，向布庄来客说明你曾出力支持。',
            'pupil-end',
            {
              minutes: 60,
              reward: { skill: 'textile', xp: 25, reputation: 1 },
            },
          ),
        ],
      },
      {
        id: 'late',
        title: '旧单已转交别家',
        person: '绣坊师傅',
        text: '线料未到，师傅把部分旧单转交邻坊。他不再收这一单，阿秀还留着自己的新样。',
        objective: '支持独立试样，或结束往来。',
        choices: [
          choose(
            'pupil',
            '再看看阿秀的新样',
            '你转向没有交期承诺的试样，先了解她的办法。',
            'new-pattern',
          ),
          choose(
            'end',
            '向师傅说明失约',
            '你没有领取这笔货款，师傅收回原来的线料单。',
            'missed-end',
          ),
        ],
      },
      end(
        'master-end',
        '绣坊的稳妥来客',
        '师傅',
        '旧订单稳妥完成，你的供货门路通向布庄。',
      ),
      end('craft-end', '选线的分寸', '师傅', '你用时间换来扎实的选线经验。'),
      end(
        'pupil-end',
        '样牌上的名字',
        '阿秀',
        '她的新样有了署名，你也掌握了新的纺织经验。这次支持没有虚构成现金收益。',
      ),
      end('missed-end', '错过的绣架', '师傅', '旧单已由别人完成，约定终止。'),
      end('declined', '未展开的鞋样', '阿秀', '你没有加入师徒的争执。'),
    ],
  },
  {
    id: 'old-house',
    title: '旧屋檐下',
    focus: 'neighbors',
    opening: 'opening',
    stages: [
      {
        id: 'opening',
        title: '雨水落进堂屋',
        person: '瓦匠老吴',
        text: '邻巷屋檐漏水，住户说得换整片瓦，老吴却怀疑是水沟堵了。两户人家都怕替对方多出钱。',
        objective: '选择组织材料，或先查漏水来源。',
        choices: [
          choose(
            'materials',
            '替两户统筹备料',
            '你请老吴列出临时挡雨所需，约好次日确认。',
            'list',
          ),
          choose(
            'inspect',
            '陪老吴查明漏点',
            '你扶稳梯子，老吴沿屋檐寻找积水留下的痕迹。',
            'leak',
            { minutes: 45, cost: { stamina: 12 } },
          ),
          leave('你没有承接修屋，两户继续等瓦匠安排。'),
        ],
      },
      {
        id: 'list',
        title: '先让屋里干下来',
        person: '老吴',
        waitMinutes: 1440,
        text: '老吴要四份柴和一匹布作临时挡雨与烘干，三日内备齐付180文。整片换瓦仍要等查明原因再说。',
        objective: '接备料或改为查漏。',
        choices: [
          choose(
            'promise',
            '接下临时备料',
            '住户凑出180文，约定三日内交齐。',
            'delivery',
          ),
          choose(
            'check',
            '先看是否需要这些料',
            '你跟老吴上梯查看，先不接备料款。',
            'leak',
            { minutes: 45, cost: { stamina: 10 } },
          ),
        ],
      },
      {
        id: 'leak',
        title: '落叶堵住的水口',
        person: '老吴',
        text: '积水正从两户共用的水口倒灌。清沟需要人扶梯与搬杂物，也需要双方同意今后轮流清理。',
        objective: '选择先动手清沟，或先协调责任。',
        choices: [
          choose(
            'clear',
            '帮老吴清出堵塞物',
            '你们搬掉湿叶，水流通了。老吴请你再与两户说清以后怎么维护。',
            'neighbors',
            { minutes: 90, cost: { stamina: 18 } },
          ),
          choose(
            'agree',
            '请两户一起确认水口归属',
            '你请双方看过水痕，商定一起出力。两户自己动手，老吴请你记录维护办法。',
            'neighbors',
            { minutes: 60, cost: { stamina: 5 }, reveal: 'shared-drain' },
          ),
        ],
      },
      {
        id: 'delivery',
        title: '临时遮雨',
        person: '两户街坊',
        deadlineMinutes: 4320,
        timeout: 'late',
        text: '四份柴和一匹布将用于烘干与遮雨，住户等你交齐后付约定款。',
        objective: '交付柴4份、布1匹，报酬180文。',
        choices: [
          choose(
            'deliver',
            '把材料交给老吴',
            '材料逐项交清，两户付180文；老吴邀你稍后看看收尾。',
            'materials-result',
            {
              destination: 'market',
              minutes: 45,
              cost: { goods: { firewood: 4, cloth: 1 } },
              reward: { cash: 180 },
            },
          ),
        ],
      },
      {
        id: 'neighbors',
        title: '两户共用一条水沟',
        person: '街坊何嫂',
        text: '漏水止住了，何嫂请你把轮流清沟的安排说给两户。老吴愿意顺便教你辨认药草烘屋时的用处。',
        objective: '把维护安排落定。',
        choices: [
          choose(
            'schedule',
            '写清轮流维护的约定',
            '两户在约定上各画一押。何嫂介绍你认识开客栈的何叔，老吴教你一些日常养护经验。',
            'neighbors-end',
            { minutes: 45, reward: { customer: 'innkeeper', reputation: 2 } },
          ),
        ],
      },
      {
        id: 'materials-result',
        title: '屋里重新生火',
        person: '老吴',
        waitMinutes: 720,
        text: '屋里已经干下来。老吴问你往后更想接材料生意，还是多认识附近的街坊。',
        objective: '选择材料机会或街坊往来。',
        choices: [
          choose(
            'supply',
            '请老吴介绍柴料货源',
            '柴铺答应五日内按每份10文供给最多六份柴。',
            'materials-end',
            {
              reward: {
                opportunity: {
                  good: 'firewood',
                  quantity: 6,
                  price: 10,
                  days: 5,
                },
              },
            },
          ),
          choose(
            'neighbors',
            '留下听街坊说旧屋',
            '何嫂带你认识客栈何叔，说明这次你按时送来材料。',
            'neighbors-end',
            { minutes: 45, reward: { customer: 'innkeeper' } },
          ),
        ],
      },
      {
        id: 'late',
        title: '雨后另作安排',
        person: '老吴',
        text: '住户从别处借来遮雨材料，180文备料约定取消。水沟仍需要清理，你可以帮忙收尾。',
        objective: '参与清沟，或结束此事。',
        choices: [
          choose(
            'clear',
            '帮忙清理雨后杂物',
            '你跟老吴重新看过水口，找到倒灌的原因。',
            'leak',
            { minutes: 30 },
          ),
          choose(
            'end',
            '说明未能备齐',
            '你与住户结清口头约定，没有领取材料款。',
            'missed-end',
          ),
        ],
      },
      end(
        'neighbors-end',
        '共用的屋檐',
        '何嫂',
        '两户有了明确的维护安排，你也通过街坊认识了客栈主人。',
      ),
      end(
        'materials-end',
        '按时送来的柴布',
        '老吴',
        '这次材料生意结束，短期柴料机会已经开放。',
      ),
      end(
        'missed-end',
        '另借的遮雨布',
        '老吴',
        '街坊另作安排，这笔备料生意没有完成。',
      ),
      end('declined', '檐下的人各有忙处', '老吴', '你没有接下修屋的事。'),
    ],
  },
  {
    id: 'guest-cook',
    title: '外乡厨客的一席饭',
    focus: 'craft',
    opening: 'opening',
    stages: [
      {
        id: 'opening',
        title: '借灶的人',
        person: '外乡厨客杜生',
        text: '杜生带来家乡的菜谱，食肆掌柜怕客人吃不惯，只肯借半日灶。杜生想保留原味，也愿意听熟悉汴梁的人说说。',
        objective: '支持原味试菜，或协助调整地方口味。',
        choices: [
          choose(
            'original',
            '先听他讲原来的做法',
            '杜生把配料与火候写给你，希望先按原样试一次。',
            'recipe',
            { minutes: 30 },
          ),
          choose(
            'local',
            '去问食客惯常的口味',
            '你问了几桌食客，记下他们对咸淡与份量的顾虑。',
            'taste',
            { minutes: 45, cost: { stamina: 5 } },
          ),
          leave('杜生继续寻找愿意帮忙试菜的人。'),
        ],
      },
      {
        id: 'recipe',
        title: '家乡的火候',
        person: '杜生',
        text: '杜生需要两份面粉和两枚蛋，不承诺买料的钱，只答应把试作经验教给你。你也可以先让他尝尝本地饼铺的做法。',
        objective: '决定投入试菜，或转向地方口味调查。',
        choices: [
          choose(
            'ingredients',
            '答应带来试菜材料',
            '杜生留好试灶的安排，等你有空备齐；这一步没有交货倒计时。',
            'trial',
          ),
          choose(
            'local',
            '带他了解本地食客',
            '杜生收起配料单，与你一道去问熟客。',
            'taste',
            { minutes: 45, cost: { stamina: 5 } },
          ),
        ],
      },
      {
        id: 'taste',
        title: '不是人人爱同一口',
        person: '食肆掌柜',
        text: '掌柜愿意让杜生减少咸味、缩小份量。懂食品手艺可一起改方，不懂也能帮忙对照食客意见。',
        objective: '确定调整后的试席方案。',
        choices: [
          choose(
            'skill',
            '依食材搭配调整方子',
            '杜生保留主要香味，改了咸淡和份量，掌柜同意安排试席。',
            'banquet',
            {
              skill: { id: 'food', level: 1 },
              minutes: 30,
              reward: { skill: 'food', xp: 5 },
            },
          ),
          choose(
            'listen',
            '逐桌核对意见再商量',
            '你把相反的意见也讲清，杜生选出一套能兼顾多数人的做法。',
            'banquet',
            { minutes: 75, cost: { stamina: 10 } },
          ),
        ],
      },
      {
        id: 'trial',
        title: '半日试灶',
        person: '杜生',
        text: '杜生等着面粉与鸡蛋。一旦开始试作，就需要你在灶旁帮忙，不能只放下材料便走。',
        objective: '交付面粉2份、鸡蛋2枚并协助试菜。',
        choices: [
          choose(
            'cook',
            '带料来试灶',
            '火候试了两遍，杜生把成败的区别讲给你，约好次日听掌柜的意见。',
            'original-result',
            {
              destination: 'market',
              minutes: 90,
              cost: { stamina: 12, goods: { flour: 2, egg: 2 } },
              reward: { skill: 'food', xp: 12 },
            },
          ),
        ],
      },
      {
        id: 'banquet',
        title: '试席的配菜',
        person: '食肆掌柜',
        deadlineMinutes: 4320,
        timeout: 'late',
        text: '掌柜给试席配了六个炊饼与两枚咸蛋的需求，三日内送到付150文。杜生负责新菜，你负责稳妥的配食。',
        objective: '交付炊饼6个、咸蛋2枚，报酬150文。',
        choices: [
          choose(
            'deliver',
            '交付试席配食',
            '掌柜验收后付150文，杜生邀请你听食客的反应。',
            'local-result',
            {
              destination: 'market',
              minutes: 45,
              cost: { goods: { bread: 6, saltedEgg: 2 } },
              reward: { cash: 150 },
            },
          ),
        ],
      },
      {
        id: 'original-result',
        title: '留住的家乡味',
        person: '杜生',
        waitMinutes: 1440,
        text: '掌柜没有把原味菜写进日常菜单，但愿意给外乡客预订。杜生感谢你让他不必一开始就丢掉家乡的做法。',
        objective: '选择学艺复盘或认识供货人。',
        choices: [
          choose(
            'learn',
            '复盘两次火候',
            '杜生把失败的一锅也仔细讲清，你学到的经验比单看成菜更多。',
            'original-end',
            { minutes: 60, reward: { skill: 'food', xp: 20 } },
          ),
          choose(
            'meet',
            '请他介绍饼铺孙娘',
            '孙娘听说你愿意认真备料，与你谈起后续供货。',
            'supplier-end',
            { minutes: 30, reward: { customer: 'baker' } },
          ),
        ],
      },
      {
        id: 'local-result',
        title: '新菜留在菜单上',
        person: '食肆掌柜',
        waitMinutes: 720,
        text: '调整后的菜得到熟客认可。杜生愿意继续改良，掌柜想找稳定的配食来源。',
        objective: '选择供货来往或继续学艺。',
        choices: [
          choose(
            'business',
            '请掌柜介绍稳定买主',
            '掌柜向孙娘提起你按时备齐试席，供货往来由此开始。',
            'supplier-end',
            { reward: { customer: 'baker' } },
          ),
          choose(
            'study',
            '与杜生整理改方经验',
            '你们把每次调整与食客反应记在一起，掌握了配餐的取舍。',
            'local-end',
            { minutes: 60, reward: { skill: 'food', xp: 20 } },
          ),
        ],
      },
      {
        id: 'late',
        title: '试席已散',
        person: '杜生',
        text: '配食由掌柜另行准备，150文的约定失效。杜生还愿意与你做一次没有交期的原味试菜。',
        objective: '回到试作，或结束这次合作。',
        choices: [
          choose(
            'retry',
            '陪杜生再看原方',
            '你从试作重新开始，原供货报酬不再有效。',
            'recipe',
            { minutes: 30 },
          ),
          choose(
            'end',
            '说明不能继续',
            '杜生收好菜谱，你没有领取未交付的货款。',
            'missed-end',
          ),
        ],
      },
      end(
        'original-end',
        '另留一页菜谱',
        '杜生',
        '家乡原味有了自己的位置，你学到的是完整的火候经验。',
      ),
      end(
        'local-end',
        '两地相逢的一味',
        '杜生',
        '新菜留在日常菜单上，改方经验已经成为你的食品手艺。',
      ),
      end(
        'supplier-end',
        '从试席到生意',
        '孙娘',
        '一次认真备食，让你认识了后续供货的买主。',
      ),
      end(
        'missed-end',
        '错过的一席饭',
        '杜生',
        '试席已经结束，这次合作未能完成。',
      ),
      end('declined', '灶火仍亮着', '杜生', '你没有答应试菜，杜生另找帮手。'),
    ],
  },
];

export const STORY_MAP = Object.fromEntries(STORIES.map((s) => [s.id, s]));
export function storyStage(definitionId: string, stageId: string) {
  const stage = STORY_MAP[definitionId]?.stages.find((s) => s.id === stageId);
  if (!stage) throw Error('故事阶段不存在');
  return stage;
}
