import type { StreetScene } from './story-types.ts';

const decline = {
  id: 'decline',
  label: '拱手告辞',
  text: '你说明眼下无法参与，没有许下新的承诺。',
  minutes: 0,
};
const scene = (s: StreetScene): StreetScene => ({
  ...s,
  choices: [...s.choices, decline],
});

/** Six story openings and ten short scenes, selected by actual operating context. */
export const STREET_SCENES: StreetScene[] = [
  scene({
    id: 'eggs-bridge',
    family: 'eggs',
    title: '桥头散落的鸡蛋',
    person: '陈婆婆',
    contexts: ['trade', 'work'],
    storyId: 'broken-eggs',
    text: '车轮擦过竹篮，蛋液沿石缝流下。陈婆婆蹲在桥头，脚夫阿成攥着食肆的木牌，急得说不清话。',
    clue: '蛋液还湿，木牌上写着附近食肆的名字。',
    inspection:
      '饼摊掌柜亲眼看见车轮擦过竹篮。阿成负责送货，食肆正在等这篮蛋。',
    inspectCash: 0,
    inspectMinutes: 10,
    choices: [
      {
        id: 'help',
        label: '给陈婆婆20文解急',
        text: '陈婆婆收下钱，记住了你的名字。她会捎来食肆欠账的口信。',
        minutes: 15,
        cost: { cash: 20 },
        reward: { reputation: 1 },
        storyStage: 'letter',
      },
      {
        id: 'escort',
        label: '帮阿成整理并护送',
        text: '你们赶到后厨，阿成想起有四枚蛋另装在一只小篮里。',
        minutes: 45,
        cost: { stamina: 12 },
        storyStage: 'porter',
      },
      {
        id: 'evidence',
        label: '查清经过再帮忙核账',
        text: '你记下证人的话，准备去食肆核对这篮蛋的去向。',
        minutes: 30,
        cost: { stamina: 5 },
        evidence: 'inspected',
        storyStage: 'audit',
      },
    ],
  }),
  scene({
    id: 'theatre-box',
    family: 'theatre',
    title: '雨中的戏衣箱',
    person: '柳七',
    contexts: ['trade'],
    storyId: 'theatre',
    text: '戏班衣箱在路边裂开，湿衣袖拖到了地上。柳七拦住你，说台口已经借好，衣服却出了事。',
    clue: '衣箱里有破衣，也有只湿了接缝的旧衣。',
    inspection: '裁缝检查后说：全换新衣费布，修旧衣费工，两条路都要有人张罗。',
    inspectCash: 0,
    inspectMinutes: 15,
    choices: [
      {
        id: 'supply',
        label: '替戏班筹新布',
        text: '柳七请衣箱师傅次日把用料单交给你。',
        minutes: 15,
        storyStage: 'measure',
      },
      {
        id: 'mend',
        label: '先帮忙晾衣看接缝',
        text: '你把衣服展开晾好，裁缝带你看容易绷线的袖口。',
        minutes: 45,
        cost: { stamina: 10 },
        storyStage: 'seams',
      },
    ],
  }),
  scene({
    id: 'granary-gate',
    family: 'granary',
    title: '粮仓门前的两辆车',
    person: '老赵',
    contexts: ['trade'],
    storyId: 'granary',
    text: '粮仓门口两辆车堵在一起。新旧掌柜各攥一张单子，卸货的挑夫等得不耐烦。',
    clue: '车牌相似，封条的颜色却不相同。',
    inspection:
      '老赵说这两车分属交接前后，仓簿混记了车次；附近磨坊的粮已经快用完。',
    inspectCash: 0,
    inspectMinutes: 15,
    choices: [
      {
        id: 'audit',
        label: '替双方核验封条',
        text: '你记下封条，老赵答应明日拿出仓簿。',
        minutes: 30,
        cost: { stamina: 5 },
        storyStage: 'seals',
      },
      {
        id: 'buyers',
        label: '先去问磨坊缺多少粮',
        text: '你绕开争吵，磨坊阿七说眼下最缺十份粟米。',
        minutes: 45,
        cost: { stamina: 8 },
        storyStage: 'buyers',
      },
    ],
  }),
  scene({
    id: 'embroidery-pattern',
    family: 'embroidery',
    title: '风里卷起的鞋样',
    person: '阿秀',
    contexts: ['trade', 'work'],
    storyId: 'embroidery',
    text: '一张鞋样被风卷到你脚边。阿秀追出来，师傅在门内喊她回去赶旧单。',
    clue: '鞋样边写着多次修改的日期，并非随手画成。',
    inspection:
      '阿秀想试自己的针路，师傅担忧的是已收定金的旧订单。双方各有难处。',
    inspectCash: 0,
    inspectMinutes: 10,
    choices: [
      {
        id: 'master',
        label: '先帮师傅理清旧单',
        text: '师傅展开订单，请你看最后还缺的线料。',
        minutes: 30,
        storyStage: 'old-order',
      },
      {
        id: 'pupil',
        label: '把鞋样还给阿秀并听她解释',
        text: '阿秀指给你看新针路，想找人帮她验证能否久穿。',
        minutes: 30,
        storyStage: 'new-pattern',
      },
    ],
  }),
  scene({
    id: 'roof-water',
    family: 'old-house',
    title: '檐下泼来的雨水',
    person: '老吴',
    contexts: ['work'],
    storyId: 'old-house',
    text: '两户街坊端着水盆站在门口，都说是对方的屋檐把水灌进自家。老吴扶着梯子，一时腾不出手。',
    clue: '两边水痕都从同一处共用水口往下延。',
    inspection: '老吴认为先查水口才能定用料，整片换瓦未必必要。',
    inspectCash: 0,
    inspectMinutes: 15,
    choices: [
      {
        id: 'materials',
        label: '替两户张罗临时备料',
        text: '老吴答应次日把用料清单交给你。',
        minutes: 15,
        storyStage: 'list',
      },
      {
        id: 'check',
        label: '扶梯陪老吴查漏',
        text: '你扶稳梯子，看见积水从塞满落叶的水口倒灌。',
        minutes: 45,
        cost: { stamina: 12 },
        storyStage: 'leak',
      },
    ],
  }),
  scene({
    id: 'cook-stove',
    family: 'guest-cook',
    title: '灶前的争执',
    person: '杜生',
    contexts: ['trade', 'work'],
    storyId: 'guest-cook',
    text: '食肆掌柜正要收回试灶的锅。外乡厨客杜生护着菜谱，说还没来得及让人尝。',
    clue: '掌柜担忧份量和咸淡，杜生在意的是家乡原来的做法。',
    inspection: '掌柜没有收试菜钱，只是不肯在不知食客反应时把新菜写进菜单。',
    inspectCash: 0,
    inspectMinutes: 15,
    choices: [
      {
        id: 'original',
        label: '请杜生先说原方',
        text: '杜生摊开配料单，请你一起准备试作。',
        minutes: 30,
        storyStage: 'recipe',
      },
      {
        id: 'local',
        label: '替两人问问食客意见',
        text: '你问过几桌客人，掌柜愿意听一套调整后的方案。',
        minutes: 45,
        cost: { stamina: 5 },
        storyStage: 'taste',
      },
    ],
  }),
  scene({
    id: 'wallet-owner',
    family: 'wallet',
    title: '钱袋上的针脚',
    person: '赶路的妇人',
    contexts: ['trade', 'work'],
    text: '你捡起一只钱袋，两个路人都说是自己的。袋口缝着一小截青线。',
    clue: '一人只报得出钱数，另一人先问青线有没有松。',
    inspection: '妇人能说出钱袋内侧的补丁位置，另一个人听见后便往人群里退。',
    inspectCash: 0,
    inspectMinutes: 10,
    choices: [
      {
        id: 'return',
        label: '核实后归还',
        text: '妇人收回钱袋，请你收下10文谢意，街坊也记住了你的认真。',
        minutes: 10,
        evidence: 'inspected',
        reward: { cash: 10, reputation: 1 },
      },
      {
        id: 'witness',
        label: '请邻铺暂存等失主',
        text: '你请邻铺当众记下钱袋特征，免得冒领。',
        minutes: 20,
        cost: { stamina: 3 },
        reward: { reputation: 1 },
      },
    ],
  }),
  scene({
    id: 'cheap-cloth',
    family: 'bargain',
    title: '卷里夹着的短布',
    person: '布贩',
    contexts: ['trade'],
    text: '布贩说有一匹尾货急着出手，不许展开太久。你看见卷边有一道接缝。',
    clue: '接缝内外颜色略有差别。',
    inspection: '展开后只有半匹可用，布贩所谓整匹是把两段短料卷在一起。',
    inspectCash: 0,
    inspectMinutes: 10,
    choices: [
      {
        id: 'expose',
        label: '请他把短料另作标记',
        text: '布贩改了标记，围看的买主少走一次冤枉路。',
        minutes: 15,
        evidence: 'inspected',
        reward: { reputation: 1 },
      },
      {
        id: 'walk',
        label: '不买未经展开的布',
        text: '你没有付款，继续看别家的货。',
        minutes: 0,
      },
    ],
  }),
  scene({
    id: 'porter-rope',
    family: 'work',
    title: '断绳的货车',
    person: '脚夫小郑',
    contexts: ['work'],
    text: '小郑的货车绳结断了，箱子歪在车沿。他愿付工钱请你一起重新捆稳。',
    clue: '箱底没有破，先卸半车再捆比较稳妥。',
    inspection: '箱上写有收货铺名，店伙计就在旁边，能当场付清约定的工钱。',
    inspectCash: 0,
    inspectMinutes: 10,
    choices: [
      {
        id: 'work',
        label: '卸货后重新捆车',
        text: '货车捆稳，小郑按约付30文。',
        minutes: 60,
        cost: { stamina: 15 },
        reward: { cash: 30 },
      },
      {
        id: 'hold',
        label: '扶住车沿等他找人',
        text: '你扶稳车沿，等店伙计叫来另一个脚夫。小郑向你道谢。',
        minutes: 20,
        cost: { stamina: 5 },
        reward: { reputation: 1 },
      },
    ],
  }),
  scene({
    id: 'diner-seat',
    family: 'meal',
    title: '一桌两张订席单',
    person: '食肆跑堂',
    contexts: ['trade'],
    text: '两家客人同时拿出订席单，跑堂忙得满脸是汗。掌柜请你帮忙看清日期。',
    clue: '一张写今日，另一张的日期旁有个补写的小字。',
    inspection: '补字是“次日”，两张单没有重订。',
    inspectCash: 0,
    inspectMinutes: 10,
    choices: [
      {
        id: 'explain',
        label: '向两家解释日期',
        text: '双方各自看清日期，掌柜付你15文答谢。',
        minutes: 15,
        evidence: 'inspected',
        reward: { cash: 15 },
      },
      {
        id: 'waiter',
        label: '帮跑堂把两家分别安顿',
        text: '你请一桌暂坐喝水，掌柜得空自己核清了单子。',
        minutes: 30,
        cost: { stamina: 5 },
        reward: { reputation: 1 },
      },
    ],
  }),
  scene({
    id: 'rain-awning',
    family: 'shelter',
    title: '被风掀起的雨棚',
    person: '摊主何嫂',
    contexts: ['trade', 'work'],
    text: '一阵风把雨棚掀起，何嫂一手护货一手拉绳，眼看就撑不住。',
    clue: '棚角绳子松了，把重物挪过去就能稳住。',
    inspection: '棚架没坏，只需重新压住两角；何嫂认得邻铺的掌柜。',
    inspectCash: 0,
    inspectMinutes: 5,
    choices: [
      {
        id: 'hold',
        label: '帮她压住棚角',
        text: '你把棚角压稳，何嫂保住了这一摊货，记下这份人情。',
        minutes: 20,
        cost: { stamina: 8 },
        reward: { reputation: 1 },
      },
      {
        id: 'call',
        label: '请邻铺一起搭手',
        text: '你叫来两位掌柜，大家一起把棚绳重新系牢。',
        minutes: 15,
        cost: { stamina: 3 },
        reward: { reputation: 1 },
      },
    ],
  }),
  scene({
    id: 'doctor-label',
    family: 'doctor',
    title: '药摊混了签',
    person: '郎中许先生',
    contexts: ['trade'],
    text: '风吹乱了药包标签，许先生拦下正要取药的客人，宁肯慢些也不愿错给。',
    clue: '标签背面有每位客人的约定记号。',
    inspection: '许先生自己能辨药，缺的是一个替他逐张核对姓名和记号的人。',
    inspectCash: 0,
    inspectMinutes: 10,
    choices: [
      {
        id: 'sort',
        label: '逐张核对标签',
        text: '许先生重新核验每一包药，付你20文，病客也不必再担心拿错。',
        minutes: 45,
        cost: { stamina: 8 },
        reward: { cash: 20 },
      },
      {
        id: 'queue',
        label: '帮客人按记号排队',
        text: '队伍排好，许先生能专心核药，街坊记住了你肯搭手。',
        minutes: 20,
        cost: { stamina: 4 },
        reward: { reputation: 1 },
      },
    ],
  }),
  scene({
    id: 'scales',
    family: 'dispute',
    title: '秤盘上的争执',
    person: '盐铺伙计',
    contexts: ['trade'],
    text: '买主说秤不准，伙计说盐受潮才压秤。双方都请你做个见证。',
    clue: '秤砣底部沾了一团泥。',
    inspection: '清掉泥后与邻铺对秤，秤砣恢复正常，盐包应当重新称过。',
    inspectCash: 0,
    inspectMinutes: 15,
    choices: [
      {
        id: 'reweigh',
        label: '见证双方重新称盐',
        text: '伙计补齐了差额，双方认同新称的数目。',
        minutes: 20,
        evidence: 'inspected',
        reward: { reputation: 2 },
      },
      {
        id: 'neighbor',
        label: '借邻铺的秤当面比较',
        text: '你跑一趟借来秤，双方自己看清差额。',
        minutes: 30,
        cost: { stamina: 5 },
        reward: { reputation: 1 },
      },
    ],
  }),
  scene({
    id: 'letter-address',
    family: 'letter',
    title: '错写巷名的家书',
    person: '驿卒',
    contexts: ['work'],
    text: '驿卒拿着家书站在路口，信上巷名差了一个字，附近两家又都姓周。',
    clue: '信封提到收信人家门前的一棵槐树。',
    inspection: '问过卖水的人，槐树下那家周木匠近日一直等着外乡的信。',
    inspectCash: 0,
    inspectMinutes: 15,
    choices: [
      {
        id: 'guide',
        label: '带驿卒去槐树下',
        text: '木匠认出家人的字，信终于送对了门。',
        minutes: 20,
        evidence: 'inspected',
        cost: { stamina: 3 },
        reward: { reputation: 1 },
      },
      {
        id: 'ask',
        label: '陪驿卒逐户核对姓名',
        text: '你们多走了一段路，仍把信交到真正的收信人手里。',
        minutes: 45,
        cost: { stamina: 8 },
        reward: { reputation: 1 },
      },
    ],
  }),
  scene({
    id: 'lantern-frame',
    family: 'lantern',
    title: '歪掉的灯架',
    person: '灯匠小陆',
    contexts: ['work'],
    text: '小陆刚立起灯架，就被过车碰歪了。他请你扶一会儿，好腾手重扎底座。',
    clue: '竹架没断，底座的绳扣松脱了。',
    inspection: '重新扎扣要半个时辰；若两人轮流抬架，能省些力气。',
    inspectCash: 0,
    inspectMinutes: 5,
    choices: [
      {
        id: 'hold',
        label: '扶架等他扎好',
        text: '灯架重新站稳，小陆付你18文。',
        minutes: 30,
        cost: { stamina: 10 },
        reward: { cash: 18 },
      },
      {
        id: 'share',
        label: '轮流抬架慢慢重扎',
        text: '你们多花些时间，少费些力气，灯架也扎得牢固。小陆付18文。',
        minutes: 60,
        cost: { stamina: 5 },
        reward: { cash: 18 },
      },
    ],
  }),
  scene({
    id: 'lost-bell',
    family: 'bell',
    title: '船坞旧铃',
    person: '补船匠',
    contexts: ['trade'],
    text: '两位船户同时来认一只旧铃。补船匠说谁能说清铃内的记号，便还给谁。',
    clue: '一位船户说铃里刻着两道短横，另一位只说声音熟。',
    inspection: '铃内确有两道短横，旧修船单也记着这个标记。',
    inspectCash: 0,
    inspectMinutes: 10,
    choices: [
      {
        id: 'verify',
        label: '按修船单见证归还',
        text: '铃回到原主船上，补船匠赞你核得认真。',
        minutes: 15,
        evidence: 'inspected',
        reward: { reputation: 1 },
      },
      {
        id: 'records',
        label: '帮匠人整理旧修船单',
        text: '你翻出相关记录，让双方自己看清记号。匠人付12文答谢。',
        minutes: 45,
        cost: { stamina: 5 },
        reward: { cash: 12 },
      },
    ],
  }),
];

export const SCENE_MAP = Object.fromEntries(
  STREET_SCENES.map((s) => [s.id, s]),
);
